version: "3"

services:
  hadoop100:
    image: wechar/hadoop
    hostname: hadoop100
    container_name: hadoop100
    command: sh -c "/dockerentry/namenode-run.sh"
    restart: always
    ports:
      - 9870:9870
      - 9864:9864
    volumes:
      - ./volumes/hadoop/data/hadoop100:/usr/share/hadoop/data
      - ./volumes/hadoop/logs/hadoop100:/usr/share/hadoop/logs
    environment:
      - CLUSTER_NAME=test
    tty: true
    networks:
      proxy:
        ipv4_address: 172.16.0.100

  hadoop101:
    image: wechar/hadoop
    hostname: hadoop101
    container_name: hadoop101
    command: sh -c "/dockerentry/resourcemanager-run.sh"
    restart: always
    ports:
      - 8088:8088
    volumes:
      - ./volumes/hadoop/data/hadoop101:/usr/share/hadoop/data
      - ./volumes/hadoop/logs/hadoop101:/usr/share/hadoop/logs
    environment:
      - PREREQUISITE_SERVERS=hadoop100-9870:hadoop102-9868
    tty: true
    networks:
      proxy:
        ipv4_address: 172.16.0.101

  hadoop102:
    image: wechar/hadoop
    hostname: hadoop102
    container_name: hadoop102
    command: sh -c "/dockerentry/secondarynamenode-run.sh"
    restart: always
    ports:
      - 9868:9868
    volumes:
      - ./volumes/hadoop/data/hadoop102:/usr/share/hadoop/data
      - ./volumes/hadoop/logs/hadoop102:/usr/share/hadoop/logs
    tty: true
    networks:
      proxy:
        ipv4_address: 172.16.0.102

networks:
  proxy:
    ipam:
      config:
        - subnet: 172.16.0.0/24
          gateway: 172.16.0.1
