version: "3"

services:
  hadoop100:
    image: wechar/hadoop
    hostname: hadoop100
    container_name: hadoop100
    user: hadoop
    command: sh -c "/dockerentry/namenode-run.sh"
    restart: always
    ports:
      - 9870:9870
      - 9864:9864
    environment:
      - CLUSTER_NAME=test
    tty: true

  hadoop101:
    image: wechar/hadoop
    hostname: hadoop101
    container_name: hadoop101
    user: hadoop
    command: sh -c "/dockerentry/resourcemanager-run.sh"
    restart: always
    ports:
      - 8088:8088
    environment:
      - PREREQUISITE_SERVERS=hadoop100-9870:hadoop102-9868
    tty: true

  hadoop102:
    image: wechar/hadoop
    hostname: hadoop102
    container_name: hadoop102
    user: hadoop
    command: sh -c "/dockerentry/secondarynamenode-run.sh"
    restart: always
    ports:
      - 9868:9868
    tty: true
